export const Categories: any = {
    GEMMES: {
        16: {
            "GEMMES facetades": {
                17: {
                    RODOLITA: 146,
                    AMETISTA: 20,
                    AMBER: 223,
                    AXINITA: 21,
                    BITOWNITA: 23,
                    CLINOHUMITA: 24,
                    "QUARS FUMAT": 46,
                    "QUARS TURMALINA": 47,
                    ESFENA: 27,
                    ESPESARTITA: 28,
                    ESPINELA: 29,
                    IOLITA: 30,
                    KUNZITA: 31,
                    KYANITA: 22,
                    LABRADORITA: 32,
                    "PEDRA INCA": 59,
                    DEMANTOIDE: 92,
                    HACKMANITA: 93,
                    MARAGDA: 204,
                    SAFIR: 94,
                    GRANAT: 95,
                    ESFALERITA: 97,
                    PEZZOTAITA: 98,
                    ANDALUCITA: 99,
                    PERIDOTO: 107,
                    AMETRI: 108,
                    SILLIMANITA: 109,
                    "GRANAT TSAVORITA": 110,
                    DIASPORO: 111,
                    ROBI: 112,
                    TURMALINA: 113,
                    GRANDIDIERITA: 114,
                    OPALO: 121,
                    "QUARS ROSA": 124,
                    ANDESINA: 139,
                    HELIODOR: 149,
                    AIGUAMARINA: 150,
                    RUBELITA: 151,
                    MICROCLINA: 154,
                    "GRANAT HESSONITA": 155,
                    APATIT: 160,
                    "GRANAT IMPERIAL": 161,
                    FLUORITA: 164,
                    TRIPLITA: 166,
                    MORGANITA: 173,
                    "GRANAT MALAY": 174,
                    "GRANAT CANVI COLOR": 175,
                    VESUVIANITA: 177,
                    CASITERITA: 178,
                    EPIDOTA: 179,
                    PARISITA: 180,
                    RUTIL: 181,
                    // PERICLINA: 182,
                    // AEGIRINE: 183,
                    MONAZITA: 184,
                    ZOISITA: 185,
                    "CITRI QUARS": 186,
                    PREHNITA: 187,
                    ZIRCON: 159,
                    ORTHOCLASA: 188,
                    THULITE: 210,
                    ZOISITE: 212,
                    CASSITERITE: 213,
                    // VESUVIANITE: 214,
                    AEGIRINE: 215,
                    // PARISITE: 216,
                    MONAZITE: 217,
                    PERICLINE: 218,
                    APOPHYLLITE: 219,
                    SCHEELITE: 220,
                    BERYLLONITE: 221,
                    AGATE: 226,
                    "BANDAGED AGATE": 227,
                    "CIRCULAR AGATE": 228,
                    "FIRE AGATE": 229,
                    "DEMETRIC AGATE": 230,
                    "MOSS AGATE": 231,
                    "ORBICULAR AGATE": 232,
                    "LANDSCAPE AGATE": 233,
                    ALABASTER: 234,
                    ANGLESITE: 235,
                    ANORTHITE: 236,
                    ARAGONITE: 237,
                    AVENTURINE: 238,
                    JET: 239,
                    AZURMALACHITE: 240,
                    "GOLDEN BERYL": 241,
                    BIXBITE: 242,
                    BRONZITE: 243,
                    BUSTAMITE: 244,
                    CALCITE: 245,
                    CELESTITE: 246,
                    CLINOZOISITE: 247,
                    CORNERUPINE: 248,
                    "BLUE QUARTZ": 249,
                    CUPRITE: 250,
                    CHROMDIOPSIDE: 251,
                    DANBURITE: 252,
                    DIAMOND: 253,
                    DIOPSIDE: 254,
                    DIOPTASE: 255,
                    DOLOMITE: 256,
                    DUMORTIERITE: 257,
                    EUDIALYTE: 258,
                    GASPEITE: 259,
                    "ALMANDINE GARNET": 260,
                    "ANDRADITE GARNET": 261,
                    HELIOTROPE: 262,
                    HEMATITE: 263,
                    HERIMORPHITE: 264,
                    HYPERSTHENE: 265,
                    LAZULITE: 266,
                    LEPIDOLITE: 267,
                    "MAN SIT SIT": 268,
                    MOOKAITE: 269,
                    NUUMITE: 270,
                    "TIGER'S EYE": 271,
                    ORTHOCLASE: 272,
                    SANIDINE: 273,
                    SEPIOLITE: 274,
                    SIDERITE: 275,
                    SMITHSONITE: 276,
                    STICHTITE: 277,
                    TITANITE: 278,
                    TUCUPITE: 279,
                    XILOPAL: 280,
                },
            },
            CABOIXIONS: {
                18: {
                    AERINITA: 58,
                    "GRANAT ESTRELLA": 62,
                    JADEITA: 43,
                    OPAL: 33,
                    "PEDRA CINTA": 50,
                    "PEDRA INCA": 51,
                    "PEDRA LLUNA": 63,
                    PIETERSITA: 52,
                    PIROXMANGITA: 76,
                    PRENITA: 48,
                    "QUARS RUTILAT": 64,
                    RODOCROSITA: 74,
                    SERPENTINA: 53,
                    "SONORA SUNRISE": 77,
                    GARNET: 205,
                    SODALITA: 75,
                    PYROMORPHITE: 206,
                    SUGILITA: 73,
                    TEFROITA: 57,
                    TURQUESA: 54,
                    XAROITA: 56,
                    JASPI: 62,
                    CALCEDONIA: 83,
                    RODONITA: 85,
                    ESFALERITA: 86,
                    OBSIDIANA: 87,
                    PERIDOT: 88,
                    "ULL DE TIGRE": 89,
                    SERAFINITA: 102,
                    "BUMBLE BEE": 103,
                    ESTROMATOLITO: 104,
                    MALAQUITA: 105,
                    GRANDIDIERITA: 115,
                    TSAVORITA: 116,
                    HESONITA: 117,
                    "QUARS ROSA": 118,
                    "QUARS AMB INCLUSIONS": 119,
                    AMATISTA: 120,
                    AIGUAMARINA: 125,
                    ALBITA: 126,
                    ESPERSATITA: 127,
                    MARAGDA: 128,
                    "GRANAT MALAY": 129,
                    CIANITA: 130,
                    "PEDRA SOL": 131,
                    CRISOPRASA: 132,
                    UNAQUITA: 134,
                    HACKMANITA: 135,
                    SAFIR: 136,
                    AMBRE: 137,
                    TURMALINA: 140,
                    VARISCITA: 142,
                    IOLITA: 144,
                    CRISOBERIL: 148,
                    QUIASTOLITA: 152,
                    ALEXANDRITA: 169,
                    "CANVI DE COLOR": 170,
                    "ULL DE GAT": 171,
                    LARIMAR: 201,
                    LAPIS: 202,
                    APATITA: 189,
                    ROBI: 198,
                    THULITE: 209,
                    TOPAZI: 224,
                    CRYSOCOLLA: 211,
                    FLUORITA: 222,
                    AGATE: 281,
                    "BANDAGED AGATE": 282,
                    "CIRCULAR AGATE": 283,
                    "FIRE AGATE": 284,
                    "DEMETRIC AGATE": 285,
                    "MOSS AGATE": 286,
                    "ORBICULAR AGATE": 287,
                    "LANDSCAPE AGATE": 288,
                    ALABASTER: 289,
                    ANGLESITE: 290,
                    ANORTHITE: 291,
                    ARAGONITE: 292,
                    AVENTURINE: 293,
                    JET: 294,
                    AZURMALACHITE: 295,
                    "GOLDEN BERYL": 296,
                    BIXBITE: 297,
                    BRONZITE: 298,
                    BUSTAMITE: 299,
                    CALCITE: 300,
                    CELESTITE: 301,
                    CLINOZOISITE: 302,
                    CORNERUPINE: 303,
                    "BLUE QUARTZ": 304,
                    CUPRITE: 305,
                    CHROMDIOPSIDE: 306,
                    DANBURITE: 307,
                    DIAMOND: 308,
                    DIOPSIDE: 309,
                    DIOPTASE: 310,
                    DOLOMITE: 311,
                    DUMORTIERITE: 312,
                    EUDIALYTE: 313,
                    GASPEITE: 314,
                    "ALMANDINE GARNET": 315,
                    "ANDRADITE GARNET": 316,
                    HELIOTROPE: 317,
                    HEMATITE: 318,
                    HERIMORPHITE: 319,
                    HYPERSTHENE: 320,
                    LAZULITE: 321,
                    LEPIDOLITE: 322,
                    "MAN SIT SIT": 323,
                    MOOKAITE: 324,
                    NUUMITE: 325,
                    "TIGER EYE": 326,
                    ORTHOCLASE: 327,
                    SANIDINE: 328,
                    SEPIOLITE: 329,
                    SIDERITE: 330,
                    SMITHSONITE: 331,
                    STICHTITE: 332,
                    TITANITE: 333,
                    TUCUPITE: 334,
                    XILOPAL: 335,
                },
            },
            CARVING: { 19: {} },
        },
    },
    "MATERIAL EN BRUT": {
        37: {
            PLAQUES: 42,
            "BRUT FACETAR": 78,
            "BRUT CABOIXONS": 81,
        },
    },
    JOIERIA: {
        38: {
            ANELLS: 13,
            COLLARETS: 34,
            ARRACADES: 66,
            BRAÇALETS: 67,
            FERMALLS: 100,
            PENJOLLS: 336,
        },
    },
    MINERALS: {
        39: {
            AERINITA: 225,
            AIGUAMARINA: 337,
            AMBRE: 340,
            AMETISTA: 339,
            AMETRI: 341,
            ANGELITA: 342,
            ATZURITA: 343,
            CALCEDONIA: 344,
            ESFALERITA: 351,
            ESTAUROLITA: 347,
            FLUORITA: 348,
            GRANATALMANDI: 362,
            GRANATANDRADITA: 363,
            GRANATCANVICOLOR: 357,
            GRANATDEMANTOIDE: 358,
            GRANATESPESSATINA: 360,
            GRANATGROSSULAR: 353,
            GRANATHESSONITE: 359,
            GRANATMALI: 356,
            GRANATRODOLITA: 354,
            GRANATTSAVORITA: 349,
            GRANATVERMELL: 361,
            GRANDIDIERITA: 364,
            JACINTOCOMPOSTELA: 373,
            MALAQUITA: 365,
            MARAGDA: 352,
            MOLDAVITA: 366,
            MORGANITA: 367,
            OBSIDIANA: 368,
            OPAL: 369,
            ORTOSA: 370,
            PAISINA: 371,
            PERIDOT: 372,
            PIRITA: 374,
            POLDERVAARTITA: 375,
            PREHNITA: 376,
            QUARSBITERMINAT: 377,
            QUARSCITRÍ: 345,
            QUARSCRISTALLROCA: 378,
            QUARSFUMAT: 350,
            QUIASTOLITA: 379,
            ROBI: 380,
            RODOCROSITA: 381,
            RUTIL: 382,
            SAFIR: 388,
            TOPAZI: 383,
            TURMALINA: 384,
            TURMALINADRAVITA: 346,
            TURQUESA: 385,
            VARISCITA: 386,
            WOLFRAMI: 387,
            ZOISITA: 390,
            ZOISITAROBI: 389,
        }
    },
    METEORITS: {
        40: {
            TECTITES: 65,
            METEORITS: 69,
        },
    },
    FOSSILS: {
        60: {
            AMBRE: 68,
            "FOSSIL VEGETAL": 72,
            "FOSSIL ANIMAL": 82,
        },
    },
    "PEDRA INCA": { 71: "" },
    ATZABEJA: { 90: "" },
    LOTS: {
        194: {
            CABOIXONS: 195,
            FACETATS: 196,
            BRUT: 197,
        }
    }
}
