export const Categories: any = {
    GEMMES: {
        16: {
            "GEMMES facetades": {
                17: {
                    RODOLITA: 146,
                    AMETISTA: 20,
                    AXINITA: 21,
                    BITOWNITA: 23,
                    CLINOHUMITA: 24,
                    "QUARS FUMAT": 46,
                    "QUARS TURMALINA": 47,
                    ESFENA: 27,
                    ESPESARTITA: 28,
                    ESPINELA: 29,
                    IOLITA: 30,
                    KUNZITA: 31,
                    KYANITA: 22,
                    LABRADORITA: 32,
                    "PEDRA INCA": 59,
                    DEMANTOIDE: 92,
                    HACKMANITA: 93,
                    MARAGDA: 204,
                    SAFIR: 94,
                    GRANAT: 95,
                    ESFALERITA: 97,
                    PEZZOTAITA: 98,
                    ANDALUCITA: 99,
                    PERIDOTO: 107,
                    AMETRI: 108,
                    SILLIMANITA: 109,
                    "GRANAT TSAVORITA": 110,
                    ZULTANITA: 111,
                    ROBI: 112,
                    TURMALINA: 113,
                    GRANDIDIERITA: 114,
                    OPALO: 121,
                    "QUARS ROSA": 124,
                    ANDESINA: 139,
                    HELIODOR: 149,
                    AIGUAMARINA: 150,
                    RUBELITA: 151,
                    MICROCLINA: 154,
                    "GRANAT HESSONITA": 155,
                    APATIT: 160,
                    "GRANAT IMPERIAL": 161,
                    FLUORITA: 164,
                    TRIPLITA: 166,
                    MORGANITA: 173,
                    "GRANAT MALAY": 174,
                    "GRANAT CANVI COLOR": 175,
                    VESUVIANITA: 177,
                    CASITERITA: 178,
                    EPIDOTA: 179,
                    PARISITA: 180,
                    RUTIL: 181,
                    PERICLINA: 182,
                    AERINITA: 183,
                    MONAZITA: 184,
                    ZOISITA: 185,
                    "CITRI QUARS": 186,
                    PREHNITA: 187,
                    ZIRCON: 159,
                    ORTHOCLASA: 188,
                },
            },
            CABOIXIONS: {
                18: {
                    AERINITA: 58,
                    "GRANAT ESTRELLA": 62,
                    JADEITA: 43,
                    OPAL: 33,
                    "PEDRA CINTA": 50,
                    "PEDRA INCA": 51,
                    "PEDRA LLUNA": 63,
                    PIETERSITA: 52,
                    PIROXMANGITA: 76,
                    PRENITA: 48,
                    "QUARS RUTILAT": 64,
                    RODOCROSITA: 74,
                    SERPENTINA: 53,
                    "SONORA SUNRISE": 77,
                    GARNET: 205,
                    SODALITA: 75,
                    SUGILITA: 73,
                    TEFROITA: 57,
                    TURQUESA: 54,
                    XAROITA: 56,
                    JASPI: 62,
                    CALCEDONIA: 83,
                    RODONITA: 85,
                    ESFALERITA: 86,
                    OBSIDIANA: 87,
                    PERIDOT: 88,
                    "ULL DE TIGRE": 89,
                    SERAFINITA: 102,
                    "BUMBLE BEE": 103,
                    ESTROMATOLITO: 104,
                    MALAQUITA: 105,
                    GRANDIDIERITA: 115,
                    TSAVORITA: 116,
                    HESONITA: 117,
                    "QUARS ROSA": 118,
                    "QUARS AMB INCLUSIONS": 119,
                    AMATISTA: 120,
                    AIGUAMARINA: 125,
                    ALBITA: 126,
                    ESPERSATITA: 127,
                    MARAGDA: 128,
                    "GRANAT MALAY": 129,
                    CIANITA: 130,
                    "PEDRA SOL": 131,
                    CRISOPRASA: 132,
                    UNAQUITA: 134,
                    HACKMANITA: 135,
                    SAFIR: 136,
                    AMBRE: 137,
                    TURMALINA: 140,
                    VARISCITA: 142,
                    IOLITA: 144,
                    CRISOBERIL: 148,
                    QUIASTOLITA: 152,
                    ALEXANDRITA: 169,
                    "CANVI DE COLOR": 170,
                    "ULL DE GAT": 171,
                    LARIMAR: 201,
                    LAPIS: 202,
                    // "ULL DE GAT": 172,
                    APATITA: 189,
                    ROBI: 198,
                },
            },
            CARVING: { 19: {} },
        },
    },
    "MATERIAL EN BRUT": {
        37: {
            PLAQUES: 42,
            "BRUT FACETAR": 78,
            "BRUT CABOIXONS": 81,
        },
    },
    JOIERIA: {
        38: {
            ANELLS: 13,
            COLLARETS: 34,
            ARRACADES: 66,
            BRAÇALETS: 67,
            FERMALLS: 100,
        },
    },
    MINERALS: {
        39: "",
    },
    METEORITS: {
        40: {
            TECTITES: 65,
            METEORITS: 69,
        },
    },
    FOSSILS: {
        60: {
            AMBRE: 68,
            "FOSSIL VEGETAL": 72,
            "FOSSIL ANIMAL": 82,
        },
    },
    "PEDRA INCA": { 71: "" },
    ATZABEJA: { 90: "" },
    LOTS: {
        194: {
            CABOIXONS: 195,
            FACETATS: 196,
            BRUT: 197,
        }
    }
}
